---
title: "Florence: To define is to limit"
output: html_notebook
---


A huge part of this work is inspired by [Georgios Karamanis code](https://github.com/gkaramanis/aRtist/tree/main/portraits). Thank you Georgios, you are the real deal!


```{r}
suppressWarnings(if (!require(pacman)) install.packages("pacman"))

pacman::p_load('tidyverse', 'magick', 'ggforce', 'ambient', 'here', 'paletteer', 'ExtDist', 'gganimate', 'MetBrewer')


```

```{r}
# Read in image and convert to grayscale
img <- image_read("florencez.jpeg") %>% 
  image_convert(type = "grayscale")

# Get dimensions of image
img_w <- image_info(img) %>% pull(width)
img_h <- image_info(img) %>% pull(height)


# Resize the longest dimension to 80 pixels
if (img_w >= img_h) {
  img <- image_resize(img, "80")
} else {
  img <- image_resize(img, ("x80"))
}


# Create array and number rows and columns
img_array <- drop(as.integer(pluck(img, 1)))
rownames(img_array) <- 1:nrow(img_array)
colnames(img_array) <- 1:ncol(img_array)


# Create data frame from array and rename column
img_df <- as.data.frame.table(img_array) %>% 
  `colnames<-`(c("y", "x", "b")) %>% 
  mutate(
    across(everything(), as.numeric),
    bf = 1 - b / 255,
    noise = gen_perlin(x, y, frequency = 0.08)
    
  )


# Colors, fill and background
col_fill <- "black"
col_bg <- "#F1E34C"
pal <- c("#264653", "#2a9d8f", "#e9c46a", "#f4a261", "#e76f51")

ggplot(img_df) +
  geom_rect(aes(xmin = x, xmax = x + bf * runif(1, 0.7, 0.9), ymin = y, ymax = y + runif(1, 0.65, 0.85)), fill = col_fill, color = NA) +
  scale_y_reverse() +
  coord_fixed(expand = FALSE) +
  theme_minimal() +
  theme(legend.position = "none") 



ggplot(img_df) +
  geom_rect(aes(xmin = x, xmax = x + bf * 0.95, ymin = y, ymax = y + 0.75), fill = "#660066", color = NA) +
  scale_y_reverse() +
  coord_fixed(expand = FALSE) +
  theme_light() +
  theme(legend.position = "none") 


ggplot(img_df) +
  #geom_contour(aes(x = x, y = y, z = bf)) +
  #geom_contour_filled(aes(x = x, y = y, z = bf)) +
  # geom_rect(aes(xmin = x, xmax = x + bf * 0.95, ymin = y, ymax = y + 0.75, fill = noise), color = NA) +
  geom_jitter(aes(x = x, y = y, color = bf, size = noise*runif(1, 0 , pi)))+
  geom_jitter(aes(x = x, y = y, color = bf, size = noise*runif(1, 0 , pi)))+
  geom_jitter(aes(x = x, y = y, color = bf, size = noise*runif(1, 0 , pi)))+
  geom_jitter(aes(x = x, y = y, size = bf, color = noise*runif(1, 0 , pi)))+
  geom_jitter(aes(x = x, y = y, size = noise*runif(1, 0 , pi)), color = "white")+
  geom_point(aes(x = x, y = y, color = bf, size = noise*runif(1, 0 , pi)))+
  scale_y_reverse() +
  coord_fixed(expand = FALSE) +
  theme_void() +
  scale_size_continuous(range = c(0, 5)) +
  scale_color_gradientn(colors =
                          paletteer::paletteer_d("ggprism::warm_pastels")
      # paletteer::paletteer_d("basetheme::minimal")                   #paletteer::paletteer_d("fishualize::Bodianus_rufus")
                          ) +
  theme(legend.position = "none") 


  ggsave("flo_18.png", device = "png", width = 12, height = 12, units = "in", dpi = 800)
```



